version: "3.8"

services:
  localstack:
    container_name: localstack_stripe_lab
    image: localstack/localstack
    ports:
      - "4566:4566"
    #extra_hosts:
    #  - "cdk-hnb659fds-assets-000000000000-us-east-1.localhost:host-gateway"
    #  - "cdk-local-assets-000000000000-us-east-1.localhost:host-gateway"
    environment:
      - SERVICES=apigateway,lambda,stepfunctions,dynamodb,cloudwatch,ssm,cloudformation,iam
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - PERSISTENCE=0
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
